name: "Create Deployment"
description: "Create and track a deployment."
inputs:
  environment:
    description: "Environment name"
    required: true
  ref:
    description: "Deployment ref"
    required: true
  token:
    description: "GitHub token"
    required: true
outputs:
  deployment:
    description: "Deployment data used by other deployment actions"
runs:
  using: "node12"
  main: "dist/index.js"
